name: backend_deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip 
          pip install -r requirements.txt
      - name: Lint
        run: | 
          black --line-length 119 app/boardGameProject/backend
          flake8 --config=.github/workflows/.flake8 app/boardGameProject/backend
          isort app/boardGameProject/backend 
      - name: Run pytest
        run: pytest app/boardGameProject/backend/geister/tests.py
  deploy:
    runs-on: ubuntu-latest
    env:
      DJANGO_SETTINGS_MODULE: boardGameProject.settings
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip 
        pip install -r requirements.txt
  
    - name: Generate deployment package
      run:  |
        cd app/boardGameProject/backend/
        zip -r deployment.zip .
        mv deployment.zip ../../../

    - name: Run string replace
      uses: frabert/replace-string-action@master
      id: format-time
      with:
        pattern: '[:\.]+'
        string: "${{ steps.current-time.outputs.time }}"
        replace-with: "-"
        flags: "g"

    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v14
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: BoardGameStudio
        environment_name: BoardGameStudio-env
        version_label: ${{ github.run_number }}
        region: ap-northeast-1
        deployment_package: ./deployment.zip